# Generated by Django 4.2.20 on 2025-03-23 17:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=254, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Enter a valid mobile number. It must be between 9 to 15 digits and can optionally start with '+'.", regex='^\\+?\\d{9,15}$')])),
                ('external_reader_id', models.PositiveIntegerField(null=True, unique=True)),
                ('rfid_card_number', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('card_expiry_date', models.DateField(null=True)),
                ('user_id', models.CharField(editable=False, max_length=15, null=True, unique=True)),
                ('user_type', models.CharField(choices=[('Inspector', 'Inspector'), ('Admin', 'Admin'), ('User', 'User'), ('Superuser', 'Superuser'), ('Assistant User', 'Assistant User'), ('Employee', 'Employee'), ('Driver', 'Driver')], max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=users.models.content_file_name)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='avatars/thumbnails/')),
                ('retrieve_password_otp', models.IntegerField(blank=True, null=True)),
                ('password_otp_expiry_date', models.DateTimeField(null=True, verbose_name='created')),
                ('status', models.CharField(choices=[('Invited', 'Invited'), ('Active', 'Active'), ('Disabled', 'Disabled'), ('Deleted', 'Deleted')], max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('inviting_key', models.CharField(blank=True, max_length=300, null=True)),
                ('invited_date', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('invite_expiry_date', models.DateTimeField(null=True, verbose_name='created')),
                ('registration_key', models.CharField(blank=True, max_length=300, null=True)),
                ('inviter', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_by_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
