# Generated by Django 4.2.20 on 2025-03-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='card_expiry_date',
        ),
        migrations.RemoveField(
            model_name='account',
            name='external_reader_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='rfid_card_number',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User'), ('Superuser', 'Superuser')], max_length=20),
        ),
    ]
