# Generated by Django 4.2.20 on 2025-03-23 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('token_blacklist', '0012_alter_outstandingtoken_user'),
        ('users', '0002_remove_account_card_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('version', models.CharField(blank=True, max_length=10, null=True)),
                ('browser', models.CharField(blank=True, max_length=50, null=True)),
                ('os', models.CharField(blank=True, max_length=50, null=True)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('logout_type', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Forced', 'Forced'), ('Refresh Token Expired', 'Refresh Token Expired')], max_length=21, null=True)),
                ('outstanding_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_token', to='token_blacklist.outstandingtoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
